openapi: 3.0.2
servers:
  - url: /v3
info:
  version: 1.0.0
  title: Starter schema
tags:
  - name: starter
    description: Starter
paths:
  /api/v1/health:
    get:
      tags:
        - starter
      summary: Получить информацию о работоспособности приложения
      description: Получить информацию о работоспособности приложения
      operationId: v1GetHealth
      responses:
        200:
          description: Успешный ответ
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DefaultSuccessResponse'
        default:
          description: Ошибка
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DefaultErrorResponse"

components:
  schemas:
    DefaultSuccessResponse:
      type: object
      required:
        - success
        - data
      properties: 
        success:
          type: boolean
          enum:
            - true
        data:
          type: object

    DefaultErrorResponse:
      type: object
      required:
        - success
        - data
        - error
      properties: 
        success:
          type: boolean
          enum:
            - false
        data:
          type: object
        error:
          type: object
          required:
            - code
            - description
          properties:
            code:
              type: string
            description:
              type: string
