definitions:
  http.ResponseError:
    properties:
      error:
        $ref: '#/definitions/http.ResponseErrorField'
      success:
        default: false
        type: boolean
    type: object
  http.ResponseErrorField:
    properties:
      code:
        type: string
      codeDescription:
        type: string
      details:
        type: string
    type: object
  http.ResponseSuccess:
    properties:
      data: {}
      success:
        default: true
        type: boolean
    type: object
  model.User:
    properties:
      email:
        type: string
      id:
        type: integer
      name:
        type: string
      status:
        type: string
    type: object
  v1.userResponseData:
    properties:
      user:
        $ref: '#/definitions/model.User'
    type: object
  v1.usersResponseData:
    properties:
      users:
        items:
          $ref: '#/definitions/model.User'
        type: array
    type: object
info:
  contact: {}
  title: Starter API.
paths:
  /api/v1/health:
    get:
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/http.ResponseSuccess'
            - properties:
                data:
                  type: object
              type: object
      summary: Проверка работоспособности сервера
      tags:
      - health
  /api/v1/users:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/http.ResponseSuccess'
            - properties:
                data:
                  $ref: '#/definitions/v1.usersResponseData'
              type: object
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/http.ResponseError'
      summary: Получение списка пользователей
      tags:
      - users
  /api/v1/users/{id}:
    get:
      parameters:
      - description: Id пользователя
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/http.ResponseSuccess'
            - properties:
                data:
                  $ref: '#/definitions/v1.userResponseData'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/http.ResponseError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/http.ResponseError'
      summary: Получение пользователя по id
      tags:
      - users
swagger: "2.0"
