definitions:
  http.ResponseSuccess:
    properties:
      data: {}
      success:
        default: true
        type: boolean
    type: object
info:
  contact: {}
  title: Starter API.
paths:
  /api/v1/health:
    get:
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/http.ResponseSuccess'
            - properties:
                data:
                  type: object
              type: object
      summary: Проверка работоспособности сервера
      tags:
      - health
swagger: "2.0"
