name: Release

on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22.2'
      - uses: actions/checkout@v4
      - uses: golangci/golangci-lint-action@v6
        with:
          version: v1.58

  build-push-image-update-container:
    needs: lint
    runs-on: ubuntu-latest
    env:
      IMAGE: cr.yandex/${{ vars.YC_REGISTRY }}:${{ github.sha }}
    steps:
      - uses: actions/checkout@v4
      - uses: yc-actions/yc-cr-login@v2
        with:
          yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}

      - run: |
          docker build -t $IMAGE .
          docker push $IMAGE

      - uses: yc-actions/yc-sls-container-deploy@v2
        with:
          yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}
          container-name: starter
          folder-id: bbauum20au7ffproop9c
          revision-image-url: $IMAGE
