openapi: 3.0.2
info:
  version: 1.0.0
  title: Starter schema
paths:
  /api/v1/health:
    get:
      tags:
        - health
      description: Получить информацию о работоспособности приложения
      operationId: V1CheckHealth
      responses:
        200:
          description: Успешный ответ
          $ref: '#/components/responses/SuccessResponse'
        default:
          description: Ошибка
          $ref: "#/components/responses/ErrorResponse"

  /api/v1/registrations:
    post:
      tags:
        - registrations
      description: Создать заявку на регистрацию пользователя
      operationId: V1CreateRegistration
      requestBody:
        $ref: '#/components/requestBodies/V1RegistrationsCreateRegistrationRequestBody'
      responses:
        200:
          description: Успешный ответ
          $ref: '#/components/responses/V1RegistrationsCreateRegistrationResponse'
        default:
          description: Ошибка
          $ref: "#/components/responses/ErrorResponse"
    patch:
      tags:
        - registrations
      description: Подтверждение заявки на регистрацию
      operationId: V1ConfirmRegistration
      requestBody:
        $ref: '#/components/requestBodies/V1RegistrationsConfirmRegistrationRequestBody'
      responses:
        200:
          description: Успешный ответ
          $ref: '#/components/responses/V1RegistrationsConfirmRegistrationResponse'
        default:
          description: Ошибка
          $ref: "#/components/responses/ErrorResponse"

  /api/v1/session:
    get:
      tags:
        - sessions
      parameters:
        - $ref: '#/components/parameters/AuthorizationToken'
      description: Получить информацию о сессии пользователя
      operationId: V1GetCurrentSession
      responses:
        200:
          description: Успешный ответ, пользователь авторизован
          $ref: '#/components/responses/SuccessResponse'
        default:
          description: Ошибка
          $ref: "#/components/responses/ErrorResponse"

  /api/v1/sessions:
    post:
      tags:
        - sessions
      description: Создание сессии пользователя
      operationId: V1CreateSession
      requestBody:
        $ref: '#/components/requestBodies/V1SessionsCreateSessionRequestBody'
      responses:
        200:
          description: Успешный ответ, пользователь авторизован
          $ref: '#/components/responses/V1SessionsCreateSessionResponse'
        default:
          description: Ошибка
          $ref: "#/components/responses/ErrorResponse"

components:
  parameters:
    AuthorizationToken:
      name: Authorization-Token
      in: header
      required: true
      schema:
        type: string

  schemas:
    SuccessResponse:
      type: object
      required:
        - success
        - data
      properties: 
        success:
          type: boolean
          enum:
            - true
        data:
          type: object

    ErrorResponse:
      type: object
      required:
        - success
        - data
        - error
      properties: 
        success:
          type: boolean
          enum:
            - false
        data:
          type: object
        error:
          type: object
          required:
            - code
            - description
          properties:
            code:
              type: string
            description:
              type: string

    V1RegistrationsCreateRegistrationRequestBody:
      type: object
      required:
        - email
      properties:
        email:
          type: string
          format: email

    V1RegistrationsCreateRegistrationResponse:
      type: object
      required:
        - success
        - data
      properties: 
        success:
          type: boolean
          enum:
            - true
        data:
          type: object
          required:
            - id
            - email
          properties: 
            id:
              type: string
            email:
              type: string
              format: email

    V1RegistrationsConfirmRegistrationRequestBody:
      type: object
      required:
        - confirmationToken
        - password
      properties:
        confirmationToken:
          type: string
        password:
          type: string
          minLength: 1

    V1RegistrationsConfirmRegistrationResponse:
      type: object
      required:
        - success
        - data
      properties: 
        success:
          type: boolean
          enum:
            - true
        data:
          type: object
          required:
            - token
          properties: 
            token:
              type: string

    V1SessionsCreateSessionRequestBody:
      type: object
      required:
        - email
        - password
      properties:
        email:
          type: string
          format: email
        password:
          type: string
          minLength: 1

    V1SessionsCreateSessionResponse:
      type: object
      required:
        - success
        - data
      properties: 
        success:
          type: boolean
          enum:
            - true
        data:
          type: object
          required:
            - token
          properties: 
            token:
              type: string

  requestBodies:
    V1RegistrationsCreateRegistrationRequestBody:
      description: Запрос для создания заявки на регистрацию
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/V1RegistrationsCreateRegistrationRequestBody'

    V1RegistrationsConfirmRegistrationRequestBody:
      description: Запрос для подтверждения регистрации, создание пользователя с заданным паролем и авторизации
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/V1RegistrationsConfirmRegistrationRequestBody'

    V1SessionsCreateSessionRequestBody:
      description: Запрос для создания сессии для пользователя
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/V1SessionsCreateSessionRequestBody'

  responses:
    SuccessResponse:
      description: Ответ при успешно выполненном запросе
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/SuccessResponse'

    ErrorResponse:
      description: Ответ при ошибке во время выполнения запроса
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'

    V1RegistrationsCreateRegistrationResponse:
      description: Ответ при успешном создании заявки на регистрацию
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/V1RegistrationsCreateRegistrationResponse'

    V1RegistrationsConfirmRegistrationResponse:
      description: Ответ при успешном подтверждении регистрации
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/V1RegistrationsConfirmRegistrationResponse'

    V1SessionsCreateSessionResponse:
      description: Ответ при успешном создании сессии
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/V1SessionsCreateSessionResponse'